export const FETCH_PRODUCTS_START = 'search/FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_OK = 'search/FETCH_PRODUCTS_OK';
export const FETCH_PRODUCTS_ERROR = 'search/FETCH_PRODUCTS_ERROR';

export const FETCH_MORE = 'search/FETCH_MORE';

export const SET_SEARCH_VALUE = 'search/SET_SEARCH_VALUE';

export const CLEAR_PRODUCTS_IDS = 'search/CLEAR_PRODUCTS_IDS';

export const CLEAR_PREVIOUS_SEARCH_RESULT = 'search/CLEAR_PREVIOUS_SEARCH_RESULT';

export const GET_COUNT_PRODUCTS_START = 'search/GET_COUNT_PRODUCTS_START';
export const GET_COUNT_PRODUCTS_OK = 'search/GET_COUNT_PRODUCTS_OK';
export const GET_COUNT_PRODUCTS_ERROR = 'search/GET_COUNT_PRODUCTS_ERROR';