export const FETCH_PRODUCTS_START = 'products/FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_OK = 'products/FETCH_PRODUCTS_OK';
export const FETCH_PRODUCTS_ERROR = 'products/FETCH_PRODUCTS_ERROR';

export const FETCH_MORE = 'products/FETCH_MORE';

export const GET_COUNT_PRODUCTS_START = 'products/GET_COUNT_PRODUCTS_START';
export const GET_COUNT_PRODUCTS_OK = 'products/GET_COUNT_PRODUCTS_OK';
export const GET_COUNT_PRODUCTS_ERROR = 'products/GET_COUNT_PRODUCTS_ERROR';